### ISSUE TITLE
[Feat] 공격 탐지 과정 ELK+Filebeat 전처리 및 최적화

### ISSUE THREAD

**Issue by chae1xxlos** [AegisLenz/AegisLenz-ELK#9]
## 🔥 Issue
공격 탐지 과정 ELK+Filebeat 전처리 및 최적화

## ✅ TODO
- [ ]  sourceIP 클러스터링
- [ ] BERT 결과 확인
- [ ] 프론트엔드 Alert 구현
- [ ] Stratus-red-team 공격 진행 후 BERT 결과 및 Alert 기능 확인
